name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux py36
            os: ubuntu-16.04
            pyversion: '3.6'
          - name: Linux py37
            os: ubuntu-latest
            pyversion: '3.7'
          - name: Linux py38
            os: ubuntu-latest
            pyversion: '3.8'
          # - name: Linux py39
          #   os: ubuntu-latest
          #   pyversion: '3.9'
          - name: MacOS py38
            os: macos-latest
            pyversion: '3.8'
          - name: Windows py38
            os: windows-latest
            pyversion: '3.8'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.pyversion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -U -r requirements.txt
            pip install -q -U black flake8 pytest
      - name: Lint (black and flake8)
        run: |
            black --check .
            flake8 .
      - name: Test with pytest
        shell: bash
        run: |
            python setup.py install
            rm -rf ./dash_slicer ./build ./egg-info
            pytest -v .
